// Shared scan-inbox protocol — no I/O. Used by the Mac receiver and tests.

import { timingSafeEqual } from 'node:crypto';

export const INBOX_VERSION = '1';
export const DEFAULT_PORT = 8787;

export const MAX_JSON_BYTES = 5 * 1024 * 1024;
export const MAX_PNG_BYTES = 16 * 1024 * 1024;
export const MAX_BUNDLE_BYTES = 40 * 1024 * 1024;
export const MAX_ID_LENGTH = 80;

export const ALLOWED_FILES = {
  'report.json': 'application/json',
  'report.txt': 'text/plain',
  'geometry-trace.json': 'application/json',
  'detector-first.png': 'image/png',
  'detector-middle.png': 'image/png',
  'detector-last.png': 'image/png',
  'detector.png': 'image/png',
  'recognition.png': 'image/png',
  'recognition-attempt-1.png': 'image/png',
  'recognition-attempt-2.png': 'image/png',
  'recognition-attempt-3.png': 'image/png',
  'recognition-card.png': 'image/png',
  'recognition-card-1.png': 'image/png',
  'recognition-card-2.png': 'image/png',
  'recognition-card-3.png': 'image/png',
  'post-lock.json': 'application/json',
  'ocr-debug.json': 'application/json',
  'title-crop.png': 'image/png',
  'title-crop-raw.png': 'image/png',
  'title-crop-ocr.png': 'image/png',
  'title-crop-1.png': 'image/png',
  'title-crop-2.png': 'image/png',
  'title-crop-3.png': 'image/png',
  'title-crop-raw-1.png': 'image/png',
  'title-crop-raw-2.png': 'image/png',
  'title-crop-raw-3.png': 'image/png',
  'title-crop-ocr-1.png': 'image/png',
  'title-crop-ocr-2.png': 'image/png',
  'title-crop-ocr-3.png': 'image/png',
  'title-crop-enhanced-1.png': 'image/png',
  'title-crop-enhanced-2.png': 'image/png',
  'title-crop-enhanced-3.png': 'image/png',
  'footer-crop.png': 'image/png',
  'type-crop.png': 'image/png',
  'fixture.json': 'application/json',
  'recognition-quad.json': 'application/json',
  'lab-compare.json': 'application/json',
  'lab-live-orch.json': 'application/json',
  'source-highres.png': 'image/png',
  'detector-input.png': 'image/png',
  'baseline-warp.png': 'image/png',
  'current-warp.png': 'image/png',
  'title-crop-baseline.png': 'image/png',
  'title-crop-current.png': 'image/png',
  'metadata.json': 'application/json',
  'ocr-results.json': 'application/json',
  'fast-source.png': 'image/png',
  'fast-overlay.png': 'image/png',
  'fast-card-744x1039.png': 'image/png',
  'photo-source.png': 'image/png',
  'photo-overlay.png': 'image/png',
  'photo-card-744x1039.png': 'image/png',
  'fast-title.png': 'image/png',
  'photo-title.png': 'image/png',
  't000-source.png': 'image/png',
  't000-overlay.png': 'image/png',
  't000-card.png': 'image/png',
  't000-title.png': 'image/png',
  't250-source.png': 'image/png',
  't250-overlay.png': 'image/png',
  't250-card.png': 'image/png',
  't250-title.png': 'image/png',
  't500-source.png': 'image/png',
  't500-overlay.png': 'image/png',
  't500-card.png': 'image/png',
  't500-title.png': 'image/png',
  't800-source.png': 'image/png',
  't800-overlay.png': 'image/png',
  't800-card.png': 'image/png',
  't800-title.png': 'image/png',
  'summary.json': 'application/json',
  'transitions.json': 'application/json',
  'swap-01-source.png': 'image/png',
  'swap-01-card.png': 'image/png',
  'swap-02-source.png': 'image/png',
  'swap-02-card.png': 'image/png',
  'swap-03-source.png': 'image/png',
  'swap-03-card.png': 'image/png',
  'swap-04-source.png': 'image/png',
  'swap-04-card.png': 'image/png',
  'swap-05-source.png': 'image/png',
  'swap-05-card.png': 'image/png',
  'swap-06-source.png': 'image/png',
  'swap-06-card.png': 'image/png',
  'swap-07-source.png': 'image/png',
  'swap-07-card.png': 'image/png',
  'swap-08-source.png': 'image/png',
  'swap-08-card.png': 'image/png',
  'swap-09-source.png': 'image/png',
  'swap-09-card.png': 'image/png',
  'swap-10-source.png': 'image/png',
  'swap-10-card.png': 'image/png',
  'deck-001-source.png': 'image/png',
  'deck-001-card.png': 'image/png',
  'deck-001-title.png': 'image/png',
  'deck-001-art.png': 'image/png',
  'deck-001-footer.png': 'image/png',
  'deck-001-detector.png': 'image/png',
  'deck-001-metadata.json': 'application/json',
  'deck-002-source.png': 'image/png',
  'deck-002-card.png': 'image/png',
  'deck-002-title.png': 'image/png',
  'deck-002-art.png': 'image/png',
  'deck-002-footer.png': 'image/png',
  'deck-002-detector.png': 'image/png',
  'deck-002-metadata.json': 'application/json',
  'deck-003-source.png': 'image/png',
  'deck-003-card.png': 'image/png',
  'deck-003-title.png': 'image/png',
  'deck-003-art.png': 'image/png',
  'deck-003-footer.png': 'image/png',
  'deck-003-detector.png': 'image/png',
  'deck-003-metadata.json': 'application/json',
  'deck-004-source.png': 'image/png',
  'deck-004-card.png': 'image/png',
  'deck-004-title.png': 'image/png',
  'deck-004-art.png': 'image/png',
  'deck-004-footer.png': 'image/png',
  'deck-004-detector.png': 'image/png',
  'deck-004-metadata.json': 'application/json',
  'deck-005-source.png': 'image/png',
  'deck-005-card.png': 'image/png',
  'deck-005-title.png': 'image/png',
  'deck-005-art.png': 'image/png',
  'deck-005-footer.png': 'image/png',
  'deck-005-detector.png': 'image/png',
  'deck-005-metadata.json': 'application/json',
  'deck-006-source.png': 'image/png',
  'deck-006-card.png': 'image/png',
  'deck-006-title.png': 'image/png',
  'deck-006-art.png': 'image/png',
  'deck-006-footer.png': 'image/png',
  'deck-006-detector.png': 'image/png',
  'deck-006-metadata.json': 'application/json',
  'deck-007-source.png': 'image/png',
  'deck-007-card.png': 'image/png',
  'deck-007-title.png': 'image/png',
  'deck-007-art.png': 'image/png',
  'deck-007-footer.png': 'image/png',
  'deck-007-detector.png': 'image/png',
  'deck-007-metadata.json': 'application/json',
  'deck-008-source.png': 'image/png',
  'deck-008-card.png': 'image/png',
  'deck-008-title.png': 'image/png',
  'deck-008-art.png': 'image/png',
  'deck-008-footer.png': 'image/png',
  'deck-008-detector.png': 'image/png',
  'deck-008-metadata.json': 'application/json',
  'deck-009-source.png': 'image/png',
  'deck-009-card.png': 'image/png',
  'deck-009-title.png': 'image/png',
  'deck-009-art.png': 'image/png',
  'deck-009-footer.png': 'image/png',
  'deck-009-detector.png': 'image/png',
  'deck-009-metadata.json': 'application/json',
  'deck-010-source.png': 'image/png',
  'deck-010-card.png': 'image/png',
  'deck-010-title.png': 'image/png',
  'deck-010-art.png': 'image/png',
  'deck-010-footer.png': 'image/png',
  'deck-010-detector.png': 'image/png',
  'deck-010-metadata.json': 'application/json',
  'deck-011-source.png': 'image/png',
  'deck-011-card.png': 'image/png',
  'deck-011-title.png': 'image/png',
  'deck-011-art.png': 'image/png',
  'deck-011-footer.png': 'image/png',
  'deck-011-detector.png': 'image/png',
  'deck-011-metadata.json': 'application/json',
  'deck-012-source.png': 'image/png',
  'deck-012-card.png': 'image/png',
  'deck-012-title.png': 'image/png',
  'deck-012-art.png': 'image/png',
  'deck-012-footer.png': 'image/png',
  'deck-012-detector.png': 'image/png',
  'deck-012-metadata.json': 'application/json',
  'deck-013-source.png': 'image/png',
  'deck-013-card.png': 'image/png',
  'deck-013-title.png': 'image/png',
  'deck-013-art.png': 'image/png',
  'deck-013-footer.png': 'image/png',
  'deck-013-detector.png': 'image/png',
  'deck-013-metadata.json': 'application/json',
  'deck-014-source.png': 'image/png',
  'deck-014-card.png': 'image/png',
  'deck-014-title.png': 'image/png',
  'deck-014-art.png': 'image/png',
  'deck-014-footer.png': 'image/png',
  'deck-014-detector.png': 'image/png',
  'deck-014-metadata.json': 'application/json',
  'deck-015-source.png': 'image/png',
  'deck-015-card.png': 'image/png',
  'deck-015-title.png': 'image/png',
  'deck-015-art.png': 'image/png',
  'deck-015-footer.png': 'image/png',
  'deck-015-detector.png': 'image/png',
  'deck-015-metadata.json': 'application/json',
  'deck-016-source.png': 'image/png',
  'deck-016-card.png': 'image/png',
  'deck-016-title.png': 'image/png',
  'deck-016-art.png': 'image/png',
  'deck-016-footer.png': 'image/png',
  'deck-016-detector.png': 'image/png',
  'deck-016-metadata.json': 'application/json',
  'deck-017-source.png': 'image/png',
  'deck-017-card.png': 'image/png',
  'deck-017-title.png': 'image/png',
  'deck-017-art.png': 'image/png',
  'deck-017-footer.png': 'image/png',
  'deck-017-detector.png': 'image/png',
  'deck-017-metadata.json': 'application/json',
  'deck-018-source.png': 'image/png',
  'deck-018-card.png': 'image/png',
  'deck-018-title.png': 'image/png',
  'deck-018-art.png': 'image/png',
  'deck-018-footer.png': 'image/png',
  'deck-018-detector.png': 'image/png',
  'deck-018-metadata.json': 'application/json',
  'deck-019-source.png': 'image/png',
  'deck-019-card.png': 'image/png',
  'deck-019-title.png': 'image/png',
  'deck-019-art.png': 'image/png',
  'deck-019-footer.png': 'image/png',
  'deck-019-detector.png': 'image/png',
  'deck-019-metadata.json': 'application/json',
  'deck-020-source.png': 'image/png',
  'deck-020-card.png': 'image/png',
  'deck-020-title.png': 'image/png',
  'deck-020-art.png': 'image/png',
  'deck-020-footer.png': 'image/png',
  'deck-020-detector.png': 'image/png',
  'deck-020-metadata.json': 'application/json',
  'deck-021-source.png': 'image/png',
  'deck-021-card.png': 'image/png',
  'deck-021-title.png': 'image/png',
  'deck-021-art.png': 'image/png',
  'deck-021-footer.png': 'image/png',
  'deck-021-detector.png': 'image/png',
  'deck-021-metadata.json': 'application/json',
  'deck-022-source.png': 'image/png',
  'deck-022-card.png': 'image/png',
  'deck-022-title.png': 'image/png',
  'deck-022-art.png': 'image/png',
  'deck-022-footer.png': 'image/png',
  'deck-022-detector.png': 'image/png',
  'deck-022-metadata.json': 'application/json',
  'deck-023-source.png': 'image/png',
  'deck-023-card.png': 'image/png',
  'deck-023-title.png': 'image/png',
  'deck-023-art.png': 'image/png',
  'deck-023-footer.png': 'image/png',
  'deck-023-detector.png': 'image/png',
  'deck-023-metadata.json': 'application/json',
  'deck-024-source.png': 'image/png',
  'deck-024-card.png': 'image/png',
  'deck-024-title.png': 'image/png',
  'deck-024-art.png': 'image/png',
  'deck-024-footer.png': 'image/png',
  'deck-024-detector.png': 'image/png',
  'deck-024-metadata.json': 'application/json',
  'deck-025-source.png': 'image/png',
  'deck-025-card.png': 'image/png',
  'deck-025-title.png': 'image/png',
  'deck-025-art.png': 'image/png',
  'deck-025-footer.png': 'image/png',
  'deck-025-detector.png': 'image/png',
  'deck-025-metadata.json': 'application/json',
  'deck-026-source.png': 'image/png',
  'deck-026-card.png': 'image/png',
  'deck-026-title.png': 'image/png',
  'deck-026-art.png': 'image/png',
  'deck-026-footer.png': 'image/png',
  'deck-026-detector.png': 'image/png',
  'deck-026-metadata.json': 'application/json',
  'deck-027-source.png': 'image/png',
  'deck-027-card.png': 'image/png',
  'deck-027-title.png': 'image/png',
  'deck-027-art.png': 'image/png',
  'deck-027-footer.png': 'image/png',
  'deck-027-detector.png': 'image/png',
  'deck-027-metadata.json': 'application/json',
  'deck-028-source.png': 'image/png',
  'deck-028-card.png': 'image/png',
  'deck-028-title.png': 'image/png',
  'deck-028-art.png': 'image/png',
  'deck-028-footer.png': 'image/png',
  'deck-028-detector.png': 'image/png',
  'deck-028-metadata.json': 'application/json',
  'deck-029-source.png': 'image/png',
  'deck-029-card.png': 'image/png',
  'deck-029-title.png': 'image/png',
  'deck-029-art.png': 'image/png',
  'deck-029-footer.png': 'image/png',
  'deck-029-detector.png': 'image/png',
  'deck-029-metadata.json': 'application/json',
  'deck-030-source.png': 'image/png',
  'deck-030-card.png': 'image/png',
  'deck-030-title.png': 'image/png',
  'deck-030-art.png': 'image/png',
  'deck-030-footer.png': 'image/png',
  'deck-030-detector.png': 'image/png',
  'deck-030-metadata.json': 'application/json',
  'deck-031-source.png': 'image/png',
  'deck-031-card.png': 'image/png',
  'deck-031-title.png': 'image/png',
  'deck-031-art.png': 'image/png',
  'deck-031-footer.png': 'image/png',
  'deck-031-detector.png': 'image/png',
  'deck-031-metadata.json': 'application/json',
  'deck-032-source.png': 'image/png',
  'deck-032-card.png': 'image/png',
  'deck-032-title.png': 'image/png',
  'deck-032-art.png': 'image/png',
  'deck-032-footer.png': 'image/png',
  'deck-032-detector.png': 'image/png',
  'deck-032-metadata.json': 'application/json',
  'deck-033-source.png': 'image/png',
  'deck-033-card.png': 'image/png',
  'deck-033-title.png': 'image/png',
  'deck-033-art.png': 'image/png',
  'deck-033-footer.png': 'image/png',
  'deck-033-detector.png': 'image/png',
  'deck-033-metadata.json': 'application/json',
  'deck-034-source.png': 'image/png',
  'deck-034-card.png': 'image/png',
  'deck-034-title.png': 'image/png',
  'deck-034-art.png': 'image/png',
  'deck-034-footer.png': 'image/png',
  'deck-034-detector.png': 'image/png',
  'deck-034-metadata.json': 'application/json',
  'deck-035-source.png': 'image/png',
  'deck-035-card.png': 'image/png',
  'deck-035-title.png': 'image/png',
  'deck-035-art.png': 'image/png',
  'deck-035-footer.png': 'image/png',
  'deck-035-detector.png': 'image/png',
  'deck-035-metadata.json': 'application/json',
  'deck-036-source.png': 'image/png',
  'deck-036-card.png': 'image/png',
  'deck-036-title.png': 'image/png',
  'deck-036-art.png': 'image/png',
  'deck-036-footer.png': 'image/png',
  'deck-036-detector.png': 'image/png',
  'deck-036-metadata.json': 'application/json',
  'deck-037-source.png': 'image/png',
  'deck-037-card.png': 'image/png',
  'deck-037-title.png': 'image/png',
  'deck-037-art.png': 'image/png',
  'deck-037-footer.png': 'image/png',
  'deck-037-detector.png': 'image/png',
  'deck-037-metadata.json': 'application/json',
  'deck-038-source.png': 'image/png',
  'deck-038-card.png': 'image/png',
  'deck-038-title.png': 'image/png',
  'deck-038-art.png': 'image/png',
  'deck-038-footer.png': 'image/png',
  'deck-038-detector.png': 'image/png',
  'deck-038-metadata.json': 'application/json',
  'deck-039-source.png': 'image/png',
  'deck-039-card.png': 'image/png',
  'deck-039-title.png': 'image/png',
  'deck-039-art.png': 'image/png',
  'deck-039-footer.png': 'image/png',
  'deck-039-detector.png': 'image/png',
  'deck-039-metadata.json': 'application/json',
  'deck-040-source.png': 'image/png',
  'deck-040-card.png': 'image/png',
  'deck-040-title.png': 'image/png',
  'deck-040-art.png': 'image/png',
  'deck-040-footer.png': 'image/png',
  'deck-040-detector.png': 'image/png',
  'deck-040-metadata.json': 'application/json',
  'deck-041-source.png': 'image/png',
  'deck-041-card.png': 'image/png',
  'deck-041-title.png': 'image/png',
  'deck-041-art.png': 'image/png',
  'deck-041-footer.png': 'image/png',
  'deck-041-detector.png': 'image/png',
  'deck-041-metadata.json': 'application/json',
  'deck-042-source.png': 'image/png',
  'deck-042-card.png': 'image/png',
  'deck-042-title.png': 'image/png',
  'deck-042-art.png': 'image/png',
  'deck-042-footer.png': 'image/png',
  'deck-042-detector.png': 'image/png',
  'deck-042-metadata.json': 'application/json',
  'deck-043-source.png': 'image/png',
  'deck-043-card.png': 'image/png',
  'deck-043-title.png': 'image/png',
  'deck-043-art.png': 'image/png',
  'deck-043-footer.png': 'image/png',
  'deck-043-detector.png': 'image/png',
  'deck-043-metadata.json': 'application/json',
  'deck-044-source.png': 'image/png',
  'deck-044-card.png': 'image/png',
  'deck-044-title.png': 'image/png',
  'deck-044-art.png': 'image/png',
  'deck-044-footer.png': 'image/png',
  'deck-044-detector.png': 'image/png',
  'deck-044-metadata.json': 'application/json',
  'deck-045-source.png': 'image/png',
  'deck-045-card.png': 'image/png',
  'deck-045-title.png': 'image/png',
  'deck-045-art.png': 'image/png',
  'deck-045-footer.png': 'image/png',
  'deck-045-detector.png': 'image/png',
  'deck-045-metadata.json': 'application/json',
  'deck-046-source.png': 'image/png',
  'deck-046-card.png': 'image/png',
  'deck-046-title.png': 'image/png',
  'deck-046-art.png': 'image/png',
  'deck-046-footer.png': 'image/png',
  'deck-046-detector.png': 'image/png',
  'deck-046-metadata.json': 'application/json',
  'deck-047-source.png': 'image/png',
  'deck-047-card.png': 'image/png',
  'deck-047-title.png': 'image/png',
  'deck-047-art.png': 'image/png',
  'deck-047-footer.png': 'image/png',
  'deck-047-detector.png': 'image/png',
  'deck-047-metadata.json': 'application/json',
  'deck-048-source.png': 'image/png',
  'deck-048-card.png': 'image/png',
  'deck-048-title.png': 'image/png',
  'deck-048-art.png': 'image/png',
  'deck-048-footer.png': 'image/png',
  'deck-048-detector.png': 'image/png',
  'deck-048-metadata.json': 'application/json',
  'deck-049-source.png': 'image/png',
  'deck-049-card.png': 'image/png',
  'deck-049-title.png': 'image/png',
  'deck-049-art.png': 'image/png',
  'deck-049-footer.png': 'image/png',
  'deck-049-detector.png': 'image/png',
  'deck-049-metadata.json': 'application/json',
  'deck-050-source.png': 'image/png',
  'deck-050-card.png': 'image/png',
  'deck-050-title.png': 'image/png',
  'deck-050-art.png': 'image/png',
  'deck-050-footer.png': 'image/png',
  'deck-050-detector.png': 'image/png',
  'deck-050-metadata.json': 'application/json',
  'deck-051-source.png': 'image/png',
  'deck-051-card.png': 'image/png',
  'deck-051-title.png': 'image/png',
  'deck-051-art.png': 'image/png',
  'deck-051-footer.png': 'image/png',
  'deck-051-detector.png': 'image/png',
  'deck-051-metadata.json': 'application/json',
  'deck-052-source.png': 'image/png',
  'deck-052-card.png': 'image/png',
  'deck-052-title.png': 'image/png',
  'deck-052-art.png': 'image/png',
  'deck-052-footer.png': 'image/png',
  'deck-052-detector.png': 'image/png',
  'deck-052-metadata.json': 'application/json',
  'deck-053-source.png': 'image/png',
  'deck-053-card.png': 'image/png',
  'deck-053-title.png': 'image/png',
  'deck-053-art.png': 'image/png',
  'deck-053-footer.png': 'image/png',
  'deck-053-detector.png': 'image/png',
  'deck-053-metadata.json': 'application/json',
  'deck-054-source.png': 'image/png',
  'deck-054-card.png': 'image/png',
  'deck-054-title.png': 'image/png',
  'deck-054-art.png': 'image/png',
  'deck-054-footer.png': 'image/png',
  'deck-054-detector.png': 'image/png',
  'deck-054-metadata.json': 'application/json',
  'deck-055-source.png': 'image/png',
  'deck-055-card.png': 'image/png',
  'deck-055-title.png': 'image/png',
  'deck-055-art.png': 'image/png',
  'deck-055-footer.png': 'image/png',
  'deck-055-detector.png': 'image/png',
  'deck-055-metadata.json': 'application/json',
  'deck-056-source.png': 'image/png',
  'deck-056-card.png': 'image/png',
  'deck-056-title.png': 'image/png',
  'deck-056-art.png': 'image/png',
  'deck-056-footer.png': 'image/png',
  'deck-056-detector.png': 'image/png',
  'deck-056-metadata.json': 'application/json',
  'deck-057-source.png': 'image/png',
  'deck-057-card.png': 'image/png',
  'deck-057-title.png': 'image/png',
  'deck-057-art.png': 'image/png',
  'deck-057-footer.png': 'image/png',
  'deck-057-detector.png': 'image/png',
  'deck-057-metadata.json': 'application/json',
  'deck-058-source.png': 'image/png',
  'deck-058-card.png': 'image/png',
  'deck-058-title.png': 'image/png',
  'deck-058-art.png': 'image/png',
  'deck-058-footer.png': 'image/png',
  'deck-058-detector.png': 'image/png',
  'deck-058-metadata.json': 'application/json',
  'deck-059-source.png': 'image/png',
  'deck-059-card.png': 'image/png',
  'deck-059-title.png': 'image/png',
  'deck-059-art.png': 'image/png',
  'deck-059-footer.png': 'image/png',
  'deck-059-detector.png': 'image/png',
  'deck-059-metadata.json': 'application/json',
  'deck-060-source.png': 'image/png',
  'deck-060-card.png': 'image/png',
  'deck-060-title.png': 'image/png',
  'deck-060-art.png': 'image/png',
  'deck-060-footer.png': 'image/png',
  'deck-060-detector.png': 'image/png',
  'deck-060-metadata.json': 'application/json',
  'deck-061-source.png': 'image/png',
  'deck-061-card.png': 'image/png',
  'deck-061-title.png': 'image/png',
  'deck-061-art.png': 'image/png',
  'deck-061-footer.png': 'image/png',
  'deck-061-detector.png': 'image/png',
  'deck-061-metadata.json': 'application/json',
  'deck-062-source.png': 'image/png',
  'deck-062-card.png': 'image/png',
  'deck-062-title.png': 'image/png',
  'deck-062-art.png': 'image/png',
  'deck-062-footer.png': 'image/png',
  'deck-062-detector.png': 'image/png',
  'deck-062-metadata.json': 'application/json',
  'deck-063-source.png': 'image/png',
  'deck-063-card.png': 'image/png',
  'deck-063-title.png': 'image/png',
  'deck-063-art.png': 'image/png',
  'deck-063-footer.png': 'image/png',
  'deck-063-detector.png': 'image/png',
  'deck-063-metadata.json': 'application/json',
  'deck-064-source.png': 'image/png',
  'deck-064-card.png': 'image/png',
  'deck-064-title.png': 'image/png',
  'deck-064-art.png': 'image/png',
  'deck-064-footer.png': 'image/png',
  'deck-064-detector.png': 'image/png',
  'deck-064-metadata.json': 'application/json',
  'deck-065-source.png': 'image/png',
  'deck-065-card.png': 'image/png',
  'deck-065-title.png': 'image/png',
  'deck-065-art.png': 'image/png',
  'deck-065-footer.png': 'image/png',
  'deck-065-detector.png': 'image/png',
  'deck-065-metadata.json': 'application/json',
  'deck-066-source.png': 'image/png',
  'deck-066-card.png': 'image/png',
  'deck-066-title.png': 'image/png',
  'deck-066-art.png': 'image/png',
  'deck-066-footer.png': 'image/png',
  'deck-066-detector.png': 'image/png',
  'deck-066-metadata.json': 'application/json',
  'deck-067-source.png': 'image/png',
  'deck-067-card.png': 'image/png',
  'deck-067-title.png': 'image/png',
  'deck-067-art.png': 'image/png',
  'deck-067-footer.png': 'image/png',
  'deck-067-detector.png': 'image/png',
  'deck-067-metadata.json': 'application/json',
  'deck-068-source.png': 'image/png',
  'deck-068-card.png': 'image/png',
  'deck-068-title.png': 'image/png',
  'deck-068-art.png': 'image/png',
  'deck-068-footer.png': 'image/png',
  'deck-068-detector.png': 'image/png',
  'deck-068-metadata.json': 'application/json',
  'deck-069-source.png': 'image/png',
  'deck-069-card.png': 'image/png',
  'deck-069-title.png': 'image/png',
  'deck-069-art.png': 'image/png',
  'deck-069-footer.png': 'image/png',
  'deck-069-detector.png': 'image/png',
  'deck-069-metadata.json': 'application/json',
  'deck-070-source.png': 'image/png',
  'deck-070-card.png': 'image/png',
  'deck-070-title.png': 'image/png',
  'deck-070-art.png': 'image/png',
  'deck-070-footer.png': 'image/png',
  'deck-070-detector.png': 'image/png',
  'deck-070-metadata.json': 'application/json',
  'deck-071-source.png': 'image/png',
  'deck-071-card.png': 'image/png',
  'deck-071-title.png': 'image/png',
  'deck-071-art.png': 'image/png',
  'deck-071-footer.png': 'image/png',
  'deck-071-detector.png': 'image/png',
  'deck-071-metadata.json': 'application/json',
  'deck-072-source.png': 'image/png',
  'deck-072-card.png': 'image/png',
  'deck-072-title.png': 'image/png',
  'deck-072-art.png': 'image/png',
  'deck-072-footer.png': 'image/png',
  'deck-072-detector.png': 'image/png',
  'deck-072-metadata.json': 'application/json',
  'deck-073-source.png': 'image/png',
  'deck-073-card.png': 'image/png',
  'deck-073-title.png': 'image/png',
  'deck-073-art.png': 'image/png',
  'deck-073-footer.png': 'image/png',
  'deck-073-detector.png': 'image/png',
  'deck-073-metadata.json': 'application/json',
  'deck-074-source.png': 'image/png',
  'deck-074-card.png': 'image/png',
  'deck-074-title.png': 'image/png',
  'deck-074-art.png': 'image/png',
  'deck-074-footer.png': 'image/png',
  'deck-074-detector.png': 'image/png',
  'deck-074-metadata.json': 'application/json',
  'deck-075-source.png': 'image/png',
  'deck-075-card.png': 'image/png',
  'deck-075-title.png': 'image/png',
  'deck-075-art.png': 'image/png',
  'deck-075-footer.png': 'image/png',
  'deck-075-detector.png': 'image/png',
  'deck-075-metadata.json': 'application/json',
  'deck-076-source.png': 'image/png',
  'deck-076-card.png': 'image/png',
  'deck-076-title.png': 'image/png',
  'deck-076-art.png': 'image/png',
  'deck-076-footer.png': 'image/png',
  'deck-076-detector.png': 'image/png',
  'deck-076-metadata.json': 'application/json',
  'deck-077-source.png': 'image/png',
  'deck-077-card.png': 'image/png',
  'deck-077-title.png': 'image/png',
  'deck-077-art.png': 'image/png',
  'deck-077-footer.png': 'image/png',
  'deck-077-detector.png': 'image/png',
  'deck-077-metadata.json': 'application/json',
  'deck-078-source.png': 'image/png',
  'deck-078-card.png': 'image/png',
  'deck-078-title.png': 'image/png',
  'deck-078-art.png': 'image/png',
  'deck-078-footer.png': 'image/png',
  'deck-078-detector.png': 'image/png',
  'deck-078-metadata.json': 'application/json',
  'deck-079-source.png': 'image/png',
  'deck-079-card.png': 'image/png',
  'deck-079-title.png': 'image/png',
  'deck-079-art.png': 'image/png',
  'deck-079-footer.png': 'image/png',
  'deck-079-detector.png': 'image/png',
  'deck-079-metadata.json': 'application/json',
  'deck-080-source.png': 'image/png',
  'deck-080-card.png': 'image/png',
  'deck-080-title.png': 'image/png',
  'deck-080-art.png': 'image/png',
  'deck-080-footer.png': 'image/png',
  'deck-080-detector.png': 'image/png',
  'deck-080-metadata.json': 'application/json',
  'deck-081-source.png': 'image/png',
  'deck-081-card.png': 'image/png',
  'deck-081-title.png': 'image/png',
  'deck-081-art.png': 'image/png',
  'deck-081-footer.png': 'image/png',
  'deck-081-detector.png': 'image/png',
  'deck-081-metadata.json': 'application/json',
  'deck-082-source.png': 'image/png',
  'deck-082-card.png': 'image/png',
  'deck-082-title.png': 'image/png',
  'deck-082-art.png': 'image/png',
  'deck-082-footer.png': 'image/png',
  'deck-082-detector.png': 'image/png',
  'deck-082-metadata.json': 'application/json',
  'deck-083-source.png': 'image/png',
  'deck-083-card.png': 'image/png',
  'deck-083-title.png': 'image/png',
  'deck-083-art.png': 'image/png',
  'deck-083-footer.png': 'image/png',
  'deck-083-detector.png': 'image/png',
  'deck-083-metadata.json': 'application/json',
  'deck-084-source.png': 'image/png',
  'deck-084-card.png': 'image/png',
  'deck-084-title.png': 'image/png',
  'deck-084-art.png': 'image/png',
  'deck-084-footer.png': 'image/png',
  'deck-084-detector.png': 'image/png',
  'deck-084-metadata.json': 'application/json',
  'deck-085-source.png': 'image/png',
  'deck-085-card.png': 'image/png',
  'deck-085-title.png': 'image/png',
  'deck-085-art.png': 'image/png',
  'deck-085-footer.png': 'image/png',
  'deck-085-detector.png': 'image/png',
  'deck-085-metadata.json': 'application/json',
  'deck-086-source.png': 'image/png',
  'deck-086-card.png': 'image/png',
  'deck-086-title.png': 'image/png',
  'deck-086-art.png': 'image/png',
  'deck-086-footer.png': 'image/png',
  'deck-086-detector.png': 'image/png',
  'deck-086-metadata.json': 'application/json',
  'deck-087-source.png': 'image/png',
  'deck-087-card.png': 'image/png',
  'deck-087-title.png': 'image/png',
  'deck-087-art.png': 'image/png',
  'deck-087-footer.png': 'image/png',
  'deck-087-detector.png': 'image/png',
  'deck-087-metadata.json': 'application/json',
  'deck-088-source.png': 'image/png',
  'deck-088-card.png': 'image/png',
  'deck-088-title.png': 'image/png',
  'deck-088-art.png': 'image/png',
  'deck-088-footer.png': 'image/png',
  'deck-088-detector.png': 'image/png',
  'deck-088-metadata.json': 'application/json',
  'deck-089-source.png': 'image/png',
  'deck-089-card.png': 'image/png',
  'deck-089-title.png': 'image/png',
  'deck-089-art.png': 'image/png',
  'deck-089-footer.png': 'image/png',
  'deck-089-detector.png': 'image/png',
  'deck-089-metadata.json': 'application/json',
  'deck-090-source.png': 'image/png',
  'deck-090-card.png': 'image/png',
  'deck-090-title.png': 'image/png',
  'deck-090-art.png': 'image/png',
  'deck-090-footer.png': 'image/png',
  'deck-090-detector.png': 'image/png',
  'deck-090-metadata.json': 'application/json',
  'deck-091-source.png': 'image/png',
  'deck-091-card.png': 'image/png',
  'deck-091-title.png': 'image/png',
  'deck-091-art.png': 'image/png',
  'deck-091-footer.png': 'image/png',
  'deck-091-detector.png': 'image/png',
  'deck-091-metadata.json': 'application/json',
  'deck-092-source.png': 'image/png',
  'deck-092-card.png': 'image/png',
  'deck-092-title.png': 'image/png',
  'deck-092-art.png': 'image/png',
  'deck-092-footer.png': 'image/png',
  'deck-092-detector.png': 'image/png',
  'deck-092-metadata.json': 'application/json',
  'deck-093-source.png': 'image/png',
  'deck-093-card.png': 'image/png',
  'deck-093-title.png': 'image/png',
  'deck-093-art.png': 'image/png',
  'deck-093-footer.png': 'image/png',
  'deck-093-detector.png': 'image/png',
  'deck-093-metadata.json': 'application/json',
  'deck-094-source.png': 'image/png',
  'deck-094-card.png': 'image/png',
  'deck-094-title.png': 'image/png',
  'deck-094-art.png': 'image/png',
  'deck-094-footer.png': 'image/png',
  'deck-094-detector.png': 'image/png',
  'deck-094-metadata.json': 'application/json',
  'deck-095-source.png': 'image/png',
  'deck-095-card.png': 'image/png',
  'deck-095-title.png': 'image/png',
  'deck-095-art.png': 'image/png',
  'deck-095-footer.png': 'image/png',
  'deck-095-detector.png': 'image/png',
  'deck-095-metadata.json': 'application/json',
  'deck-096-source.png': 'image/png',
  'deck-096-card.png': 'image/png',
  'deck-096-title.png': 'image/png',
  'deck-096-art.png': 'image/png',
  'deck-096-footer.png': 'image/png',
  'deck-096-detector.png': 'image/png',
  'deck-096-metadata.json': 'application/json',
  'deck-097-source.png': 'image/png',
  'deck-097-card.png': 'image/png',
  'deck-097-title.png': 'image/png',
  'deck-097-art.png': 'image/png',
  'deck-097-footer.png': 'image/png',
  'deck-097-detector.png': 'image/png',
  'deck-097-metadata.json': 'application/json',
  'deck-098-source.png': 'image/png',
  'deck-098-card.png': 'image/png',
  'deck-098-title.png': 'image/png',
  'deck-098-art.png': 'image/png',
  'deck-098-footer.png': 'image/png',
  'deck-098-detector.png': 'image/png',
  'deck-098-metadata.json': 'application/json',
  'deck-099-source.png': 'image/png',
  'deck-099-card.png': 'image/png',
  'deck-099-title.png': 'image/png',
  'deck-099-art.png': 'image/png',
  'deck-099-footer.png': 'image/png',
  'deck-099-detector.png': 'image/png',
  'deck-099-metadata.json': 'application/json',
  'deck-100-source.png': 'image/png',
  'deck-100-card.png': 'image/png',
  'deck-100-title.png': 'image/png',
  'deck-100-art.png': 'image/png',
  'deck-100-footer.png': 'image/png',
  'deck-100-detector.png': 'image/png',
  'deck-100-metadata.json': 'application/json',
  'p01-metadata.json': 'application/json',
  'p01-f001.png': 'image/png',
  'p01-f002.png': 'image/png',
  'p01-f003.png': 'image/png',
  'p01-f004.png': 'image/png',
  'p01-f005.png': 'image/png',
  'p01-f006.png': 'image/png',
  'p01-f007.png': 'image/png',
  'p01-f008.png': 'image/png',
  'p01-f009.png': 'image/png',
  'p01-f010.png': 'image/png',
  'p01-f011.png': 'image/png',
  'p01-f012.png': 'image/png',
  'p01-f013.png': 'image/png',
  'p01-f014.png': 'image/png',
  'p01-f015.png': 'image/png',
  'p01-f016.png': 'image/png',
  'p01-f017.png': 'image/png',
  'p01-f018.png': 'image/png',
  'p01-f019.png': 'image/png',
  'p01-f020.png': 'image/png',
  'p02-metadata.json': 'application/json',
  'p02-f001.png': 'image/png',
  'p02-f002.png': 'image/png',
  'p02-f003.png': 'image/png',
  'p02-f004.png': 'image/png',
  'p02-f005.png': 'image/png',
  'p02-f006.png': 'image/png',
  'p02-f007.png': 'image/png',
  'p02-f008.png': 'image/png',
  'p02-f009.png': 'image/png',
  'p02-f010.png': 'image/png',
  'p02-f011.png': 'image/png',
  'p02-f012.png': 'image/png',
  'p02-f013.png': 'image/png',
  'p02-f014.png': 'image/png',
  'p02-f015.png': 'image/png',
  'p02-f016.png': 'image/png',
  'p02-f017.png': 'image/png',
  'p02-f018.png': 'image/png',
  'p02-f019.png': 'image/png',
  'p02-f020.png': 'image/png',
  'p03-metadata.json': 'application/json',
  'p03-f001.png': 'image/png',
  'p03-f002.png': 'image/png',
  'p03-f003.png': 'image/png',
  'p03-f004.png': 'image/png',
  'p03-f005.png': 'image/png',
  'p03-f006.png': 'image/png',
  'p03-f007.png': 'image/png',
  'p03-f008.png': 'image/png',
  'p03-f009.png': 'image/png',
  'p03-f010.png': 'image/png',
  'p03-f011.png': 'image/png',
  'p03-f012.png': 'image/png',
  'p03-f013.png': 'image/png',
  'p03-f014.png': 'image/png',
  'p03-f015.png': 'image/png',
  'p03-f016.png': 'image/png',
  'p03-f017.png': 'image/png',
  'p03-f018.png': 'image/png',
  'p03-f019.png': 'image/png',
  'p03-f020.png': 'image/png',
  'p04-metadata.json': 'application/json',
  'p04-f001.png': 'image/png',
  'p04-f002.png': 'image/png',
  'p04-f003.png': 'image/png',
  'p04-f004.png': 'image/png',
  'p04-f005.png': 'image/png',
  'p04-f006.png': 'image/png',
  'p04-f007.png': 'image/png',
  'p04-f008.png': 'image/png',
  'p04-f009.png': 'image/png',
  'p04-f010.png': 'image/png',
  'p04-f011.png': 'image/png',
  'p04-f012.png': 'image/png',
  'p04-f013.png': 'image/png',
  'p04-f014.png': 'image/png',
  'p04-f015.png': 'image/png',
  'p04-f016.png': 'image/png',
  'p04-f017.png': 'image/png',
  'p04-f018.png': 'image/png',
  'p04-f019.png': 'image/png',
  'p04-f020.png': 'image/png',
  'p05-metadata.json': 'application/json',
  'p05-f001.png': 'image/png',
  'p05-f002.png': 'image/png',
  'p05-f003.png': 'image/png',
  'p05-f004.png': 'image/png',
  'p05-f005.png': 'image/png',
  'p05-f006.png': 'image/png',
  'p05-f007.png': 'image/png',
  'p05-f008.png': 'image/png',
  'p05-f009.png': 'image/png',
  'p05-f010.png': 'image/png',
  'p05-f011.png': 'image/png',
  'p05-f012.png': 'image/png',
  'p05-f013.png': 'image/png',
  'p05-f014.png': 'image/png',
  'p05-f015.png': 'image/png',
  'p05-f016.png': 'image/png',
  'p05-f017.png': 'image/png',
  'p05-f018.png': 'image/png',
  'p05-f019.png': 'image/png',
  'p05-f020.png': 'image/png',
  'p06-metadata.json': 'application/json',
  'p06-f001.png': 'image/png',
  'p06-f002.png': 'image/png',
  'p06-f003.png': 'image/png',
  'p06-f004.png': 'image/png',
  'p06-f005.png': 'image/png',
  'p06-f006.png': 'image/png',
  'p06-f007.png': 'image/png',
  'p06-f008.png': 'image/png',
  'p06-f009.png': 'image/png',
  'p06-f010.png': 'image/png',
  'p06-f011.png': 'image/png',
  'p06-f012.png': 'image/png',
  'p06-f013.png': 'image/png',
  'p06-f014.png': 'image/png',
  'p06-f015.png': 'image/png',
  'p06-f016.png': 'image/png',
  'p06-f017.png': 'image/png',
  'p06-f018.png': 'image/png',
  'p06-f019.png': 'image/png',
  'p06-f020.png': 'image/png',
  'p07-metadata.json': 'application/json',
  'p07-f001.png': 'image/png',
  'p07-f002.png': 'image/png',
  'p07-f003.png': 'image/png',
  'p07-f004.png': 'image/png',
  'p07-f005.png': 'image/png',
  'p07-f006.png': 'image/png',
  'p07-f007.png': 'image/png',
  'p07-f008.png': 'image/png',
  'p07-f009.png': 'image/png',
  'p07-f010.png': 'image/png',
  'p07-f011.png': 'image/png',
  'p07-f012.png': 'image/png',
  'p07-f013.png': 'image/png',
  'p07-f014.png': 'image/png',
  'p07-f015.png': 'image/png',
  'p07-f016.png': 'image/png',
  'p07-f017.png': 'image/png',
  'p07-f018.png': 'image/png',
  'p07-f019.png': 'image/png',
  'p07-f020.png': 'image/png',
  'p08-metadata.json': 'application/json',
  'p08-f001.png': 'image/png',
  'p08-f002.png': 'image/png',
  'p08-f003.png': 'image/png',
  'p08-f004.png': 'image/png',
  'p08-f005.png': 'image/png',
  'p08-f006.png': 'image/png',
  'p08-f007.png': 'image/png',
  'p08-f008.png': 'image/png',
  'p08-f009.png': 'image/png',
  'p08-f010.png': 'image/png',
  'p08-f011.png': 'image/png',
  'p08-f012.png': 'image/png',
  'p08-f013.png': 'image/png',
  'p08-f014.png': 'image/png',
  'p08-f015.png': 'image/png',
  'p08-f016.png': 'image/png',
  'p08-f017.png': 'image/png',
  'p08-f018.png': 'image/png',
  'p08-f019.png': 'image/png',
  'p08-f020.png': 'image/png',
  'p09-metadata.json': 'application/json',
  'p09-f001.png': 'image/png',
  'p09-f002.png': 'image/png',
  'p09-f003.png': 'image/png',
  'p09-f004.png': 'image/png',
  'p09-f005.png': 'image/png',
  'p09-f006.png': 'image/png',
  'p09-f007.png': 'image/png',
  'p09-f008.png': 'image/png',
  'p09-f009.png': 'image/png',
  'p09-f010.png': 'image/png',
  'p09-f011.png': 'image/png',
  'p09-f012.png': 'image/png',
  'p09-f013.png': 'image/png',
  'p09-f014.png': 'image/png',
  'p09-f015.png': 'image/png',
  'p09-f016.png': 'image/png',
  'p09-f017.png': 'image/png',
  'p09-f018.png': 'image/png',
  'p09-f019.png': 'image/png',
  'p09-f020.png': 'image/png',
  'p10-metadata.json': 'application/json',
  'p10-f001.png': 'image/png',
  'p10-f002.png': 'image/png',
  'p10-f003.png': 'image/png',
  'p10-f004.png': 'image/png',
  'p10-f005.png': 'image/png',
  'p10-f006.png': 'image/png',
  'p10-f007.png': 'image/png',
  'p10-f008.png': 'image/png',
  'p10-f009.png': 'image/png',
  'p10-f010.png': 'image/png',
  'p10-f011.png': 'image/png',
  'p10-f012.png': 'image/png',
  'p10-f013.png': 'image/png',
  'p10-f014.png': 'image/png',
  'p10-f015.png': 'image/png',
  'p10-f016.png': 'image/png',
  'p10-f017.png': 'image/png',
  'p10-f018.png': 'image/png',
  'p10-f019.png': 'image/png',
  'p10-f020.png': 'image/png',
};

const SAFE_ID = /^[a-zA-Z0-9][a-zA-Z0-9._-]{0,79}$/;
const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

export const isSafeId = (value) =>
  typeof value === 'string' && value.length > 0 && value.length <= MAX_ID_LENGTH && SAFE_ID.test(value);

export const sanitizeId = (value, fallback) => {
  if (isSafeId(value)) return value;
  if (fallback && isSafeId(fallback)) return fallback;
  return null;
};

export const timingSafeEqualToken = (expected, provided) => {
  if (typeof expected !== 'string' || typeof provided !== 'string') return false;
  const a = Buffer.from(expected, 'utf8');
  const b = Buffer.from(provided, 'utf8');
  if (a.length !== b.length) {
    // Compare anyway so length leaks are not a cheap oracle.
    const dummy = Buffer.alloc(a.length);
    b.copy(dummy, 0, 0, Math.min(b.length, dummy.length));
    timingSafeEqual(a, dummy);
    return false;
  }
  return timingSafeEqual(a, b);
};

export const parseBearer = (header) => {
  if (typeof header !== 'string') return null;
  const m = header.match(/^Bearer\s+(\S+)\s*$/i);
  return m ? m[1] : null;
};

export const pairingUrl = (url, token) =>
  `lugin-debug://pair?url=${encodeURIComponent(url)}&token=${encodeURIComponent(token)}`;

export const pairingUrlAlt = (url, token) =>
  `lugin://pair-debug?url=${encodeURIComponent(url)}&token=${encodeURIComponent(token)}`;

export const parsePairInput = (raw) => {
  if (typeof raw !== 'string' || !raw.trim()) return null;
  const text = raw.trim();
  try {
    const parsed = new URL(text);
    const pairHost =
      (parsed.protocol === 'lugin:' && parsed.hostname === 'pair-debug') ||
      (parsed.protocol === 'lugin-debug:' && (parsed.hostname === 'pair' || parsed.pathname === '//pair'));
    if (pairHost) {
      const url = parsed.searchParams.get('url') ?? '';
      const token = parsed.searchParams.get('token') ?? '';
      if (url && token) return { token, url };
    }
  } catch {
    /* not a URL */
  }
  return null;
};

export const decodeFilePayload = (name, file) => {
  if (!file || typeof file !== 'object') return { ok: false, reason: 'missing file' };
  const expectedMime = ALLOWED_FILES[name];
  if (!expectedMime) return { ok: false, reason: `unexpected file ${name}` };
  const mime = typeof file.mime === 'string' ? file.mime : expectedMime;
  if (mime !== expectedMime) return { ok: false, reason: `invalid mime for ${name}` };

  let bytes;
  if (typeof file.text === 'string') {
    bytes = Buffer.from(file.text, 'utf8');
  } else if (typeof file.base64 === 'string') {
    try {
      bytes = Buffer.from(file.base64, 'base64');
    } catch {
      return { ok: false, reason: `invalid base64 for ${name}` };
    }
  } else {
    return { ok: false, reason: `no payload for ${name}` };
  }

  if (expectedMime === 'image/png') {
    if (bytes.length > MAX_PNG_BYTES) return { ok: false, reason: `png too large: ${name}` };
    if (bytes.length < PNG_MAGIC.length || !bytes.subarray(0, 8).equals(PNG_MAGIC)) {
      return { ok: false, reason: `not a png: ${name}` };
    }
  } else if (expectedMime === 'image/jpeg') {
    if (bytes.length > MAX_PNG_BYTES) return { ok: false, reason: `jpeg too large: ${name}` };
    if (bytes.length < 3 || bytes[0] !== 0xff || bytes[1] !== 0xd8 || bytes[2] !== 0xff) {
      return { ok: false, reason: `not a jpeg: ${name}` };
    }
  } else {
    if (bytes.length > MAX_JSON_BYTES) return { ok: false, reason: `text too large: ${name}` };
  }
  return { bytes, mime: expectedMime, ok: true };
};

export const validateUploadBody = (body) => {
  if (!body || typeof body !== 'object' || Array.isArray(body)) {
    return { ok: false, reason: 'invalid body' };
  }
  const sessionId = sanitizeId(body.sessionId);
  const traceId = sanitizeId(body.traceId);
  if (!sessionId) return { ok: false, reason: 'invalid sessionId' };
  if (!traceId) return { ok: false, reason: 'invalid traceId' };
  const files = body.files;
  if (!files || typeof files !== 'object' || Array.isArray(files)) {
    return { ok: false, reason: 'files required' };
  }
  const names = Object.keys(files);
  if (!names.length) return { ok: false, reason: 'files empty' };
  const decoded = {};
  let total = 0;
  for (const name of names) {
    if (name.includes('/') || name.includes('\\') || name.includes('..')) {
      return { ok: false, reason: 'path traversal' };
    }
    const one = decodeFilePayload(name, files[name]);
    if (!one.ok) return one;
    total += one.bytes.length;
    if (total > MAX_BUNDLE_BYTES) return { ok: false, reason: 'bundle too large' };
    decoded[name] = one;
  }
  return {
    ok: true,
    sessionId,
    traceId,
    createdAt: typeof body.createdAt === 'string' ? body.createdAt : new Date().toISOString(),
    device: typeof body.device === 'string' ? body.device.slice(0, 200) : null,
    appStamp: typeof body.appStamp === 'string' ? body.appStamp.slice(0, 120) : null,
    runtimeFingerprint:
      typeof body.runtimeFingerprint === 'string' ? body.runtimeFingerprint.slice(0, 80) : null,
    scannerPhase: typeof body.scannerPhase === 'string' ? body.scannerPhase.slice(0, 40) : null,
    traceType: typeof body.traceType === 'string' ? body.traceType.slice(0, 40) : 'unknown',
    files: decoded,
  };
};

export const sampleCountFromFiles = (files) => {
  const geo = files['geometry-trace.json'];
  if (!geo?.bytes) return null;
  try {
    const json = JSON.parse(geo.bytes.toString('utf8'));
    return json.meta?.sampleCount ?? json.samples?.length ?? null;
  } catch {
    return null;
  }
};

export const latestPointer = (meta, relativePath) => ({
  appStamp: meta.appStamp,
  createdAt: meta.createdAt,
  path: relativePath,
  sampleCount: meta.sampleCount ?? null,
  scannerPhase: meta.scannerPhase,
  sessionId: meta.sessionId,
  traceId: meta.traceId,
  traceType: meta.traceType,
});
